%{
// ---------------------------------------------------------------------------------------
// Copyright(c) 2025 Jens Kallup
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files(the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify,
// merge, publish, distribute, sublicense, and /or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to the following
// conditions :
// 
// The above copyright notice and this permission notice shall be included in all copies
// or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
// PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
// CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
// OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ---------------------------------------------------------------------------------------

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <ctype.h>
#include <limits.h>
#include <sys/types.h>

#include <iostream>
#include <cstring>
#include <cstdlib>
#include <cstdint>
#include <string>
#include <regex>
#include <exception>

#define YYDEBUG 0

#include "dbase.tab.hh"

//-- Forward declerations ----------------------------------
void Number();
void HexaNumber();

void count(void);

extern int yyerror(const char*);

//-- Compiler declerations ---------------------------------
bool found_header = false;


int line_row  = 1;
int line_col  = 1;
%}

%option noyywrap
%option caseless

DOUBLE_DIGIT [0-9]+\.[0-9]+
DIGIT        [0-9]+
HEXALETTER   [a-fA-F]
HEXANUMBER   [0][x](({DIGIT}|{HEXALETTER})+)
NUM          {DIGIT}+
WS           [ \t\n\r]*
ID           [a-z_]+[a-zA-Z0-9_]*
REMS1        ((\/\/.*)|(\&\&.*)|(\/\/.*\n*)|(\&\&.*\n*))*
REMS2        ((\/\*\*\/)|(\/\*(\n*|.*)\*\/))*
REMSER       {WS}{REMS1}|{REMS2}{WS}

%x COMMENTS HEADER
%%

\/\/(.*|.*\n)     { count(); BEGIN(INITIAL); }
\&\&(.*|.*\n)     { count(); BEGIN(INITIAL); }
\*\*              { count(); BEGIN(HEADER);  }

\/\*              { count(); BEGIN(COMMENTS); }
<COMMENTS>\*\/    { count(); BEGIN(INITIAL);  }
<COMMENTS>\n      { count(); }
<COMMENTS>.       { count(); }

<HEADER>\s*"END HEADER"  { count();
  if (found_header)
  yyerror("header marker already exists.");
  
  std::cout << "header found" <<
  std::endl ;
  
  found_header = true;
}
<HEADER>\n               { count(); BEGIN(INITIAL); }
<HEADER>.                { count(); }

\.      { count(); yylval.str = new std::string("."  );  return '.'; }
\,      { count(); yylval.str = new std::string(","  );  return ','; }

\=      { std::cout << "================" << std::endl; count(); yylval.str = new std::string("= " );  return CMD_ASSIGN; }
\:\=    { count(); yylval.str = new std::string(":= ");  return CMD_ASSIGN; }

"'"([^'\\]|\\.)*"'"      {
    yylval.str = new std::string(yytext + 1, yyleng - 2);
    return CMD_SQSTRING;
}

\"([^"\\]|\\.)*\"        {
    yylval.str = new std::string(yytext + 1, yyleng - 2);
    return CMD_DQSTRING;
}

\[([^\\\]]|\\.|[\n])*?\] {
    std::string raw(yytext);
    yylval.str = new std::string(raw.substr(1, raw.length() - 2));
    return CMD_BLOCKSTRING;
}
                          
"^(.*/)?(?:$|(.+?)(?:(\.[^.]*$)|$))?"  { count(); return FILENAME; }

{DOUBLE_DIGIT}  { std::cout << "double ---------------  " << yytext << std::endl; count();     Number(); return CMD_NUMBER; }
{NUM}           { count();     Number(); return CMD_NUMBER; }
{HEXANUMBER}    { count(); HexaNumber(); return CMD_NUMBER; }

{ID}  {
std::cout << yytext << std::endl;
    std::string upper = yytext;
    std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
    
    count();
    yylval.str = new std::string(yytext); 
    
    if (upper == "PARAMETER")   { return CMD_PARAMETER; }
    if (upper == "LOCAL")       { return CMD_LOCAL;     }
    
    if (upper == "IF")          { return CMD_IF;        }
    if (upper == "ELSE")        { return CMD_ELSE;      }
    if (upper == "ENDIF")       { return CMD_ENDIF;     }
    
    if (upper == "PUBLIC")      { return CMD_PUBLIC;    }
    if (upper == "PRIVATE")     { return CMD_PRIVATE;   }
    if (upper == "PROTECTED")   { return CMD_PROTECTED; }
    
    if (upper == "WITH")        { return CMD_WITH;      }
    if (upper == "ENDWITH")     { return CMD_ENDWITH;   }
    
    if (upper == "NEW")         { return CMD_NEW;       }
    if (upper == "CLASS")       { return CMD_CLASS;     }
    if (upper == "OF")          { return CMD_OF;        }
    if (upper == "ENDCLASS")    { return CMD_ENDCLASS;  }
    
    if (upper == "FORM")        { return CMD_FORM;      }
    
    return CMD_ID;
}

"!="    { count(); yylval.str = new std::string("!="); return CMD_NE;   }
"=>"    { count(); yylval.str = new std::string("=>"); return CMD_EG;   }
"=<"    { count(); yylval.str = new std::string("=<"); return CMD_EL;   }
"=="    { count(); yylval.str = new std::string("=="); return CMD_EQ;   }
">="    { count(); yylval.str = new std::string(">="); return CMD_GE;   }
"<="    { count(); yylval.str = new std::string("<="); return CMD_LE;   }

[>]     { count(); yylval.str = new std::string(">");  return CMD_GT;   }
[<]     { count(); yylval.str = new std::string("<");  return CMD_LT;   }

[+]     { count(); yylval.str = new std::string("+");  return '+';      }
[-]     { count(); yylval.str = new std::string("-");  return '-';      }
[*]     { count(); yylval.str = new std::string("*");  return '*';      }
[/]     { count(); yylval.str = new std::string("/");  return '/';      }

[(]     { count(); yylval.str = new std::string("(");  return '(';      }
[)]     { count(); yylval.str = new std::string(")");  return ')';      }

[ \t]               { count(); }
[\r\n|\n]           { count(); }

<<EOF>>             { return 0; }
.                   ;
%%

void Number () {
    yylval.val_int32 = atol(yytext);
    yylval.str = new std::string(yytext); 
}

void HexaNumber () {
    yylval.val_int32 = (unsigned int) strtol(yytext, (char **)NULL, 16);
}

void count(void)
{
    int i;
    for (i = 0; yytext[i] != '\0'; i++) {
	    if (yytext[i] == '\n')  { line_col  = 0; ++line_row; } else
	    if (yytext[i] == '\t')  { line_col += 8;             } else line_col++;
    }
}

